<?php

namespace AppBundle\Repository;

/**
 * AmortizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmortizationRepository extends \Doctrine\ORM\EntityRepository
{
}
