<?php

namespace AppBundle\Repository;

/**
 * DebitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitRepository extends \Doctrine\ORM\EntityRepository
{
}
