<?php

namespace AppBundle\Repository;

/**
 * FinancialPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
