<?php

namespace AppBundle\Repository;

/**
 * RightGoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RightGoodsRepository extends \Doctrine\ORM\EntityRepository
{
}
