<?php

namespace AppBundle\Repository;

/**
 * SavingPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavingPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
