childaccount_index:
    path:     /
    defaults: { _controller: "AppBundle:ChildAccount:index" }
    methods:  GET

childaccount_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ChildAccount:show" }
    methods:  GET

childaccount_new:
    path:     /new
    defaults: { _controller: "AppBundle:ChildAccount:new" }
    methods:  [GET, POST]

childaccount_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ChildAccount:edit" }
    methods:  [GET, POST]

childaccount_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ChildAccount:delete" }
    methods:  DELETE
