debt_index:
    path:     /
    defaults: { _controller: "AppBundle:Debt:index" }
    methods:  GET

debt_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Debt:show" }
    methods:  GET

debt_new:
    path:     /new
    defaults: { _controller: "AppBundle:Debt:new" }
    methods:  [GET, POST]

debt_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Debt:edit" }
    methods:  [GET, POST]

debt_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Debt:delete" }
    methods:  [GET, DELETE]
