income_index:
    path:     /
    defaults: { _controller: "AppBundle:Income:index" }
    methods:  GET

income_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Income:show" }
    methods:  GET

income_new:
    path:     /new
    defaults: { _controller: "AppBundle:Income:new" }
    methods:  [GET, POST]

income_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Income:edit" }
    methods:  [GET, POST]

income_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Income:delete" }
    methods:  DELETE
