rightgoods_index:
    path:     /
    defaults: { _controller: "AppBundle:RightGoods:index" }
    methods:  GET

rightgoods_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RightGoods:show" }
    methods:  GET

rightgoods_new:
    path:     /new
    defaults: { _controller: "AppBundle:RightGoods:new" }
    methods:  [GET, POST]

rightgoods_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:RightGoods:edit" }
    methods:  [GET, POST]

rightgoods_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:RightGoods:delete" }
    methods:  [GET, DELETE]
