fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

dashboard:
    path: /dashboard/
    defaults: { _controller: AppBundle:DashBoard:index }
    
app_debit:
    resource: "@AppBundle/Resources/config/routing/debit.yml"
    prefix:   /dashboard/debit
    
app_income:
    resource: "@AppBundle/Resources/config/routing/income.yml"
    prefix:   /dashboard/income

app_matrixaccount:
    resource: "@AppBundle/Resources/config/routing/matrixaccount.yml"
    prefix:   /dashboard/matrixaccount

app_childaccount:
    resource: "@AppBundle/Resources/config/routing/childaccount.yml"
    prefix:   /dashboard/childaccount

app_accounttype:
    resource: "@AppBundle/Resources/config/routing/accounttype.yml"
    prefix:   /dashboard/accounttype

app_home:
    path: /
    defaults: { _controller: AppBundle:DashBoard:home }

app_amortization:
    resource: "@AppBundle/Resources/config/routing/amortization.yml"
    prefix:   /dashboard/amortization

app_saving:
    resource: "@AppBundle/Resources/config/routing/saving.yml"
    prefix:   /dashboard/saving

app_expenditure:
    resource: "@AppBundle/Resources/config/routing/expenditure.yml"
    prefix:   /dashboard/expenditure

app_debt:
    resource: "@AppBundle/Resources/config/routing/debt.yml"
    prefix:   /dashboard/debt

app_savingplan:
    resource: "@AppBundle/Resources/config/routing/savingplan.yml"
    prefix:   /dashboard/savingplan

app_rightgoods:
    resource: "@AppBundle/Resources/config/routing/rightgoods.yml"
    prefix:   /dashboard/rightgoods

app_users:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:  /dashboard/users

user_profile:
    path:   /dashboard/profile
    defaults: { _controller: "AppBundle:User:profile" }

user_change_password:
    path:  /dashboard/change_password
    defaults: { _controller: "AppBundle:User:changePassword" }