savingplan_index:
    path:     /
    defaults: { _controller: "AppBundle:SavingPlan:index" }
    methods:  GET

savingplan_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SavingPlan:show" }
    methods:  GET

savingplan_new:
    path:     /new
    defaults: { _controller: "AppBundle:SavingPlan:new" }
    methods:  [GET, POST]

savingplan_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SavingPlan:edit" }
    methods:  [GET, POST]

savingplan_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SavingPlan:delete" }
    methods:  [GET, DELETE]
