saving_index:
    path:     /
    defaults: { _controller: "AppBundle:Saving:index" }
    methods:  GET

saving_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Saving:show" }
    methods:  GET

saving_new:
    path:     /new
    defaults: { _controller: "AppBundle:Saving:new" }
    methods:  [GET, POST]

saving_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Saving:edit" }
    methods:  [GET, POST]

saving_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Saving:delete" }
    methods:  GET
