user_index:
    path:     /
    defaults: { _controller: AppBundle:User:index }

user_new:
    path:     /new
    defaults: { _controller: AppBundle:User:new }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle:User:edit }

user_delete:
    path:    /{id}/remove
    defaults: { _controller: AppBundle:User:delete }